// import './common'
import * as Common from './common/index'
export { Common }
export * from './network'
export * from './adhoc/login'
export * from './adhoc/logout'
export * from './room/open'
export * from './room/join'
export * from './room/close'
export * from './room/leave'
export * from './room/changeid'
export * from './admin/admin'
export * from './user/get'
export * from './user/set'

import './common'
// import './network'
// import './adhoc/login'
// import './adhoc/logout'
// import './room/open'
// import './room/join'
// import './room/close'
// import './room/leave'
// import './room/changeid'


